"""
hr_routes.py — HR Module: Employee & Contractor CRUD
"""
import base64, io, json
from flask import Blueprint, render_template, redirect, url_for, request, flash, jsonify
from flask_login import login_required, current_user
from audit_helper import audit, snapshot
from datetime import datetime
from models import db, User, Employee, Contractor
from permissions import get_perm, get_grid_columns, save_grid_columns

hr = Blueprint('hr', __name__, url_prefix='/hr')


def _parse_date(val):
    try:
        return datetime.strptime(val, '%Y-%m-%d').date() if val else None
    except ValueError:
        return None


# Default grid columns
EMP_COLS_DEFAULT = ['employee_code','full_name','mobile','email','department',
                    'designation','employee_type','date_of_joining','status','qr']
EMP_COLS_ALL = {
    'employee_code':  'Emp Code',
    'full_name':      'Name',
    'mobile':         'Mobile',
    'email':          'Email',
    'department':     'Department',
    'designation':    'Designation',
    'employee_type':  'Type',
    'date_of_joining':'Date of Joining',
    'location':       'Location',
    'is_contractor':  'Contractor?',
    'marital_status': 'Marital Status',
    'blood_group':    'Blood Group',
    'status':         'Status',
    'qr':             'QR Code',
}


# ══════════════════════════════════════
# EMPLOYEE
# ══════════════════════════════════════

@hr.route('/employees')
@login_required
def employees():
    perm = get_perm('hr_employees')
    if not perm or not perm.can_view:
        flash('Access denied.', 'error'); return redirect(url_for('dashboard'))

    search  = request.args.get('search', '')
    dept    = request.args.get('dept', '')
    status  = request.args.get('status', '')
    emptype = request.args.get('emptype', '')

    q = Employee.query
    if search:
        q = q.filter(
            Employee.first_name.ilike(f'%{search}%') |
            Employee.last_name.ilike(f'%{search}%') |
            Employee.employee_code.ilike(f'%{search}%') |
            Employee.mobile.ilike(f'%{search}%') |
            Employee.email.ilike(f'%{search}%')
        )
    if dept:    q = q.filter_by(department=dept)
    if status:  q = q.filter_by(status=status)
    if emptype: q = q.filter_by(employee_type=emptype)

    emps      = q.order_by(Employee.created_at.desc()).all()
    all_depts = [r[0] for r in db.session.query(Employee.department).distinct().all() if r[0]]
    grid_cols = get_grid_columns('employees', EMP_COLS_DEFAULT, list(EMP_COLS_ALL.keys()))

    return render_template('hr/employees/index.html',
        employees=emps, perm=perm, active_page='hr_employees',
        search=search, dept=dept, status=status, emptype=emptype,
        all_depts=all_depts, grid_cols=grid_cols, all_cols=EMP_COLS_ALL)


@hr.route('/employees/grid-config', methods=['POST'])
@login_required
def emp_grid_config():
    cols = request.json.get('cols', [])
    save_grid_columns('employees', cols)
    return jsonify(success=True)


@hr.route('/employees/save-qr', methods=['POST'])
@login_required
def emp_save_qr():
    """Save QR code generated by browser JS"""
    data   = request.json
    emp_id = data.get('emp_id')
    qr_b64 = data.get('qr_base64', '').strip()
    if not emp_id or not qr_b64:
        return jsonify(success=False, error='Missing data')
    e = Employee.query.get_or_404(emp_id)
    e.qr_code_base64 = qr_b64
    db.session.commit()
    return jsonify(success=True)


@hr.route('/employees/add', methods=['GET', 'POST'])
@login_required
def emp_add():
    perm = get_perm('hr_employees')
    if not perm or not perm.can_add:
        flash('Access denied.', 'error'); return redirect(url_for('hr.employees'))

    contractors = Contractor.query.filter_by(status=1, is_deleted=0).order_by(Contractor.company_name).all()

    if request.method == 'POST':
        emp_code = request.form.get('employee_code', '').strip()
        if not emp_code:
            flash('Employee Code is required.', 'error')
            return redirect(url_for('hr.emp_add'))

        if Employee.query.filter(Employee.employee_code.ilike(emp_code)).first():
            flash(f'Employee code "{emp_code}" already exists.', 'error')
            return redirect(url_for('hr.emp_add'))

        photo   = request.form.get('photo_base64', '').strip() or None
        qr_b64  = request.form.get('qr_base64', '').strip() or None

        e = Employee(
            employee_code   = emp_code,
            first_name      = request.form.get('first_name', '').strip(),
            last_name       = request.form.get('last_name', '').strip(),
            mobile          = request.form.get('mobile', '').strip(),
            email           = request.form.get('email', '').strip(),
            gender          = request.form.get('gender', ''),
            profile_photo   = photo,
            qr_code_base64  = qr_b64,
            linkedin        = request.form.get('linkedin', '').strip(),
            facebook        = request.form.get('facebook', '').strip(),
            department      = request.form.get('department', '').strip(),
            designation     = request.form.get('designation', '').strip(),
            employee_type   = request.form.get('employee_type', ''),
            date_of_joining = _parse_date(request.form.get('date_of_joining')),
            location        = request.form.get('location', '').strip(),
            is_contractor   = request.form.get('is_contractor') == 'yes',
            contractor_id   = int(request.form['contractor_id']) if request.form.get('contractor_id') and request.form.get('is_contractor') == 'yes' else None,
            date_of_birth   = _parse_date(request.form.get('date_of_birth')),
            blood_group     = request.form.get('blood_group', '').strip(),
            marital_status  = request.form.get('marital_status', ''),
            is_block        = request.form.get('is_block') == 'yes',
            is_late         = request.form.get('is_late') == 'yes',
            is_probation    = request.form.get('is_probation') == 'yes',
            status          = request.form.get('status', 'active'),
            remark          = request.form.get('remark', '').strip(),
            created_by      = current_user.id,
        )
        db.session.add(e)
        db.session.flush()

        if request.form.get('create_user') == 'yes':
            uname = emp_code.lower().replace('-', '').replace(' ', '')
            if not User.query.filter_by(username=uname).first():
                u = User(
                    username  = uname,
                    email     = e.email or f'{uname}@hcp.com',
                    full_name = e.full_name,
                    role      = 'user',
                    is_active = True
                )
                u.set_password('HCP@123')
                db.session.add(u)
                db.session.flush()
                e.user_id = u.id

        db.session.commit()
        flash(f'Employee {emp_code} added!', 'success')
        return redirect(url_for('hr.employees'))

    return render_template('hr/employees/form.html',
        employee=None, contractors=contractors, perm=perm, active_page='hr_employees')


@hr.route('/employees/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def emp_edit(id):
    perm = get_perm('hr_employees')
    if not perm or not perm.can_edit:
        flash('Access denied.', 'error'); return redirect(url_for('hr.employees'))

    e = Employee.query.get_or_404(id)
    contractors = Contractor.query.filter_by(status=1, is_deleted=0).order_by(Contractor.company_name).all()

    if request.method == 'POST':
        photo  = request.form.get('photo_base64', '').strip()
        if photo: e.profile_photo = photo

        qr_b64 = request.form.get('qr_base64', '').strip()
        if qr_b64: e.qr_code_base64 = qr_b64

        # Employee code: editable only if currently blank
        new_code = request.form.get('employee_code', '').strip()
        if not e.employee_code and new_code:
            if Employee.query.filter(Employee.employee_code.ilike(new_code), Employee.id != e.id).first():
                flash(f'Code "{new_code}" already in use.', 'error')
                return redirect(url_for('hr.emp_edit', id=id))
            e.employee_code = new_code

        e.first_name     = request.form.get('first_name', e.first_name).strip()
        e.last_name      = request.form.get('last_name', e.last_name).strip()
        e.mobile         = request.form.get('mobile', e.mobile).strip()
        e.email          = request.form.get('email', '').strip()
        e.gender         = request.form.get('gender', '')
        e.linkedin       = request.form.get('linkedin', '').strip()
        e.facebook       = request.form.get('facebook', '').strip()
        e.department     = request.form.get('department', '').strip()
        e.designation    = request.form.get('designation', '').strip()
        e.employee_type  = request.form.get('employee_type', '')
        e.location       = request.form.get('location', '').strip()
        e.is_contractor  = request.form.get('is_contractor') == 'yes'
        cid              = request.form.get('contractor_id') or None
        e.contractor_id  = int(cid) if cid and e.is_contractor else None
        e.date_of_joining= _parse_date(request.form.get('date_of_joining'))
        e.date_of_birth  = _parse_date(request.form.get('date_of_birth'))
        e.blood_group    = request.form.get('blood_group', '').strip()
        e.marital_status = request.form.get('marital_status', '')
        e.is_block       = request.form.get('is_block') == 'yes'
        e.is_late        = request.form.get('is_late') == 'yes'
        e.is_probation   = request.form.get('is_probation') == 'yes'
        e.status         = request.form.get('status', 'active')
        e.remark         = request.form.get('remark', '').strip()
        e.updated_at     = datetime.utcnow()

        db.session.commit()
        flash('Employee updated!', 'success')
        return redirect(url_for('hr.employees'))

    return render_template('hr/employees/form.html',
        employee=e, contractors=contractors, perm=perm, active_page='hr_employees')


@hr.route('/employees/<int:id>/view')
@login_required
def emp_view(id):
    perm = get_perm('hr_employees')
    if not perm or not perm.can_view:
        flash('Access denied.', 'error'); return redirect(url_for('hr.employees'))
    e = Employee.query.get_or_404(id)
    audit('employees','VIEW', id, f'{e.employee_code or id} / {e.full_name}', obj=e)
    return render_template('hr/employees/view.html', employee=e, perm=perm, active_page='hr_employees')


@hr.route('/employees/<int:id>/delete', methods=['POST'])
@login_required
def emp_delete(id):
    perm = get_perm('hr_employees')
    if not perm or not perm.can_delete:
        flash('Access denied.', 'error'); return redirect(url_for('hr.employees'))
    e = Employee.query.get_or_404(id)
    name = e.full_name
    db.session.delete(e)
    db.session.commit()
    flash(f'Employee "{name}" deleted.', 'success')
    return redirect(url_for('hr.employees'))


@hr.route('/employees/<int:id>/regenerate-qr', methods=['POST'])
@login_required
def regen_qr(id):
    """QR is now generated client-side; this just clears the stored QR so form re-generates"""
    e = Employee.query.get_or_404(id)
    return jsonify(success=True, employee_code=e.employee_code or '')


# ══════════════════════════════════════
# CONTRACTOR
# ══════════════════════════════════════

@hr.route('/contractors')
@login_required
def contractors():
    perm = get_perm('hr_contractors')
    if not perm or not perm.can_view:
        flash('Access denied.', 'error'); return redirect(url_for('dashboard'))

    search = request.args.get('search', '')
    status = request.args.get('status', '')
    q = Contractor.query.filter_by(is_deleted=0)
    if search:
        q = q.filter(
            Contractor.company_name.ilike(f'%{search}%') |
            Contractor.contact_person.ilike(f'%{search}%') |
            Contractor.contract_id.ilike(f'%{search}%') |
            Contractor.contact_no.ilike(f'%{search}%')
        )
    if status != '':
        q = q.filter_by(status=int(status))

    ctrs = q.order_by(Contractor.created_date.desc()).all()
    return render_template('hr/contractors/index.html',
        contractors=ctrs, perm=perm, active_page='hr_contractors',
        search=search, status=status)


@hr.route('/contractors/add', methods=['GET', 'POST'])
@login_required
def contractor_add():
    perm = get_perm('hr_contractors')
    if not perm or not perm.can_add:
        flash('Access denied.', 'error'); return redirect(url_for('hr.contractors'))

    if request.method == 'POST':
        last = Contractor.query.order_by(Contractor.id.desc()).first()
        num  = (last.id + 1) if last else 1
        c = Contractor(
            company_name   = request.form.get('company_name', '').strip(),
            supply         = request.form.get('supply', '').strip(),
            pancard        = request.form.get('pancard', '').strip(),
            gstno          = request.form.get('gstno', '').strip(),
            remarks        = request.form.get('remarks', '').strip(),
            contract_id    = f"CTR-{num:04d}",
            contact_person = request.form.get('contact_person', '').strip(),
            contact_no     = request.form.get('contact_no', '').strip(),
            email_address  = request.form.get('email_address', '').strip(),
            address        = request.form.get('address', '').strip(),
            status         = 1,
            created_by     = current_user.full_name or current_user.username,
        )
        db.session.add(c)
        db.session.commit()
        flash(f'Contractor {c.contract_id} added!', 'success')
        return redirect(url_for('hr.contractors'))

    return render_template('hr/contractors/form.html',
        contractor=None, perm=perm, active_page='hr_contractors')


@hr.route('/contractors/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def contractor_edit(id):
    perm = get_perm('hr_contractors')
    if not perm or not perm.can_edit:
        flash('Access denied.', 'error'); return redirect(url_for('hr.contractors'))

    c = Contractor.query.get_or_404(id)
    if request.method == 'POST':
        c.company_name   = request.form.get('company_name', '').strip()
        c.supply         = request.form.get('supply', '').strip()
        c.pancard        = request.form.get('pancard', '').strip()
        c.gstno          = request.form.get('gstno', '').strip()
        c.remarks        = request.form.get('remarks', '').strip()
        c.contact_person = request.form.get('contact_person', '').strip()
        c.contact_no     = request.form.get('contact_no', '').strip()
        c.email_address  = request.form.get('email_address', '').strip()
        c.address        = request.form.get('address', '').strip()
        c.status         = int(request.form.get('status', 1))
        c.modified_by    = current_user.full_name or current_user.username
        c.modified_date  = datetime.utcnow()
        db.session.commit()
        flash('Contractor updated!', 'success')
        return redirect(url_for('hr.contractors'))

    return render_template('hr/contractors/form.html',
        contractor=c, perm=perm, active_page='hr_contractors')


@hr.route('/contractors/<int:id>/delete', methods=['POST'])
@login_required
def contractor_delete(id):
    perm = get_perm('hr_contractors')
    if not perm or not perm.can_delete:
        flash('Access denied.', 'error'); return redirect(url_for('hr.contractors'))
    c = Contractor.query.get_or_404(id)
    c.is_deleted = 1
    c.modified_by = current_user.full_name or current_user.username
    db.session.commit()
    flash(f'Contractor "{c.company_name}" deleted.', 'success')
    return redirect(url_for('hr.contractors'))
