"""
npd_whatsapp_auto.py
─────────────────────
NPD Daily Report — Auto WhatsApp Sender

Responsibilities:
  1. Build personalised messages per employee (their own stats)
  2. Build manager summary message (full team view)
  3. Send to all NPD employees' registered mobile numbers
  4. Log every send attempt in npd_whatsapp_send_log
  5. APScheduler integration — schedule daily send at configured time

Schedule setup (called once from index.py):
    from npd_whatsapp_auto import start_whatsapp_scheduler
    start_whatsapp_scheduler(app)
"""

import json
import logging
from datetime import datetime, date, timedelta
from typing import List, Dict, Optional

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────
# Message Builders
# ─────────────────────────────────────────────────────────────

def build_employee_message(emp_name: str, emp_stats: dict, report_date: date, rank: int = 0) -> str:
    """
    Personal WhatsApp message sent to each NPD team member.
    Shows only their own performance — private and motivating.
    """
    date_str  = report_date.strftime('%d %b %Y')
    completed = emp_stats.get('tasks_completed', 0)
    updated   = emp_stats.get('tasks_updated', 0)
    milestones= emp_stats.get('milestones_updated', 0)
    comments  = emp_stats.get('comments_added', 0)
    time_lbl  = emp_stats.get('time_label', '0m')
    score     = emp_stats.get('score', 0)

    # Motivational suffix based on score
    if score >= 80:
        emoji_line = '🏆 Outstanding performance! Keep it up!'
    elif score >= 60:
        emoji_line = '💪 Great work today!'
    elif score >= 40:
        emoji_line = '👍 Good effort — aage badho!'
    elif score > 0:
        emoji_line = '📌 Kuch kaam hua — kal aur better karo!'
    else:
        emoji_line = '📋 Aaj koi activity record nahi hui.'

    rank_line = f'🥇 *Team Rank: #{rank}*\n' if rank and rank <= 3 else ''

    msg = (
        f'📋 *NPD Daily Report — {date_str}*\n'
        f'━━━━━━━━━━━━━━━━━━━━━\n'
        f'👤 *{emp_name}*\n\n'
        f'✅ Tasks Completed:   *{completed}*\n'
        f'🔄 Tasks Updated:     *{updated}*\n'
        f'🎯 Milestones Done:   *{milestones}*\n'
        f'💬 Comments Added:    *{comments}*\n'
        f'⏱️ Time Active:       *{time_lbl}*\n'
        f'📊 Productivity Score: *{score:.0f}/100*\n'
        f'━━━━━━━━━━━━━━━━━━━━━\n'
        f'{rank_line}'
        f'{emoji_line}\n'
        f'━━━━━━━━━━━━━━━━━━━━━\n'
        f'_HCP ERP — NPD Module_'
    )
    return msg


def build_manager_summary(report: dict, report_date: date) -> str:
    """
    Full summary message for the NPD Manager.
    Includes team-wide stats + per-employee breakdown.
    """
    date_str = report_date.strftime('%d %b %Y')

    total    = report.get('total_tasks_worked', 0)
    done     = report.get('completed_tasks', 0)
    pending  = report.get('pending_tasks', 0)
    late     = report.get('late_tasks', 0)
    new_t    = report.get('new_tasks_today', 0)
    active_e = report.get('active_employees', 0)
    time_lbl = report.get('total_time_label', '0m')
    top      = report.get('top_employee') or {}

    late_line = f'⚠️ Late Tasks:    *{late}*\n' if late else ''

    # Employee breakdown (top 10)
    emp_lines = []
    for i, e in enumerate(report.get('employee_summary', [])[:10], 1):
        name  = e.get('name', '?').split()
        fname = name[0] if name else '?'
        c     = e.get('completed', 0)
        u     = e.get('updated', 0)
        s     = e.get('score', 0)
        medal = {1:'🥇', 2:'🥈', 3:'🥉'}.get(i, f'{i}.')
        parts = []
        if c: parts.append(f'{c} done')
        if u: parts.append(f'{u} updated')
        if not parts: parts = ['active']
        emp_lines.append(f'  {medal} {fname} → {", ".join(parts)} (score: {s:.0f})')

    top_line = ''
    if top:
        top_line = (f'\n🏆 *Top Performer:* {top.get("name","—")} '
                    f'(score: {top.get("score",0):.0f})\n')

    msg = (
        f'📋 *NPD Daily Report — {date_str}*\n'
        f'━━━━━━━━━━━━━━━━━━━━━\n'
        f'📊 Total Worked:  *{total}*\n'
        f'✅ Completed:     *{done}*\n'
        f'⏳ Pending:       *{pending}*\n'
        f'🆕 New Today:     *{new_t}*\n'
        f'👥 Active Team:   *{active_e}*\n'
        f'⏱️ Team Time:     *{time_lbl}*\n'
        f'{late_line}'
        f'━━━━━━━━━━━━━━━━━━━━━\n'
        f'👤 *Team Performance:*\n'
        + '\n'.join(emp_lines or ['  (No activity today)'])
        + top_line
        + '━━━━━━━━━━━━━━━━━━━━━\n'
        f'_Generated by HCP ERP — NPD Module_'
    )
    return msg


# ─────────────────────────────────────────────────────────────
# Core Send Function
# ─────────────────────────────────────────────────────────────

def send_daily_reports(app, for_date: date = None, triggered_by: int = None) -> dict:
    """
    Main function — generates report and sends WhatsApp messages.
    Called by:
      - APScheduler (automatic daily)
      - /npd/api/send-whatsapp-now (manual trigger from UI)

    Returns summary dict with send results.
    """
    with app.app_context():
        from models import db, User
        from models.employee import Employee
        from models.npd_daily_report import (
            NPDDailyReport, NPDEmployeeProductivity,
            NPDWhatsAppConfig, NPDWhatsAppSendLog,
        )
        from whatsapp_sender import WhatsAppConfig, send_whatsapp
        from npd_daily_report_routes import _build_report_for_date

        for_date = for_date or date.today()
        logger.info(f'[NPD WA] Starting daily send for {for_date}')

        # ── 1. Load WhatsApp config ──────────────────────────────
        cfg = WhatsAppConfig.from_db()
        if not cfg.enabled:
            logger.warning('[NPD WA] WhatsApp sending is disabled')
            return {'ok': False, 'error': 'WhatsApp sending disabled in config'}

        # ── 2. Ensure daily report is generated ─────────────────
        report_row = NPDDailyReport.query.filter_by(report_date=for_date).first()
        if not report_row:
            try:
                report_row, _ = _build_report_for_date(for_date)
                db.session.commit()
            except Exception as e:
                logger.error(f'[NPD WA] Report generation failed: {e}')
                return {'ok': False, 'error': f'Report generation failed: {e}'}

        try:
            report_data = json.loads(report_row.report_data or '{}')
        except Exception:
            report_data = {}

        emp_summary = {
            e['user_id']: e for e in report_data.get('employee_summary', [])
        }
        ranked_ids = [e['user_id'] for e in report_data.get('employee_summary', [])]

        results = {'sent': [], 'failed': [], 'skipped': []}

        # ── 3. Send to employees ─────────────────────────────────
        if cfg.send_to_employees:
            # Get all NPD-department employees with mobile numbers
            npd_emps = Employee.query.filter(
                Employee.is_deleted == False,
                Employee.status == 'active',
                Employee.mobile != None,
                Employee.mobile != '',
                db.or_(
                    Employee.department.ilike('%npd%'),
                    Employee.department.ilike('%management%'),
                    Employee.department.ilike('%r&d%'),
                    Employee.department.ilike('%rd%'),
                )
            ).all()

            for emp in npd_emps:
                if not emp.user_id:
                    results['skipped'].append({'name': emp.first_name, 'reason': 'No user account linked'})
                    continue

                stats    = emp_summary.get(emp.user_id, {})
                rank_pos = (ranked_ids.index(emp.user_id) + 1) if emp.user_id in ranked_ids else 0

                full_name = f'{emp.first_name} {emp.last_name}'.strip()
                message   = build_employee_message(full_name, stats, for_date, rank=rank_pos)

                result = send_whatsapp(to=emp.mobile, message=message, config=cfg)

                # Log the attempt
                log_entry = NPDWhatsAppSendLog(
                    send_date     = for_date,
                    recipient_type= 'employee',
                    recipient_name= full_name,
                    mobile_number = emp.mobile,
                    user_id       = emp.user_id,
                    message_type  = 'personal_report',
                    status        = 'sent' if result['ok'] else 'failed',
                    error_message = result.get('error', ''),
                    message_id    = result.get('message_id', ''),
                    triggered_by  = triggered_by,
                )
                db.session.add(log_entry)

                if result['ok']:
                    results['sent'].append({'name': full_name, 'number': emp.mobile})
                    logger.info(f'[NPD WA] Sent to {full_name} ({emp.mobile})')
                else:
                    results['failed'].append({'name': full_name, 'error': result.get('error', '')})
                    logger.warning(f'[NPD WA] Failed for {full_name}: {result.get("error")}')

        # ── 4. Send summary to managers ──────────────────────────
        if cfg.send_to_manager:
            manager_msg = build_manager_summary(report_data, for_date)

            # All users with npd_manager / admin role who have an employee record
            mgr_users = User.query.filter(
                User.is_active == True,
                User.role.in_(['npd_manager', 'admin', 'manager'])
            ).all()

            mgr_numbers_sent = set()

            for mgr in mgr_users:
                emp_rec = Employee.query.filter_by(user_id=mgr.id, is_deleted=False).first()
                mobile  = emp_rec.mobile if emp_rec else None

                if not mobile or mobile in mgr_numbers_sent:
                    continue
                mgr_numbers_sent.add(mobile)

                result = send_whatsapp(to=mobile, message=manager_msg, config=cfg)
                log_entry = NPDWhatsAppSendLog(
                    send_date     = for_date,
                    recipient_type= 'manager',
                    recipient_name= mgr.full_name or mgr.username,
                    mobile_number = mobile,
                    user_id       = mgr.id,
                    message_type  = 'manager_summary',
                    status        = 'sent' if result['ok'] else 'failed',
                    error_message = result.get('error', ''),
                    message_id    = result.get('message_id', ''),
                    triggered_by  = triggered_by,
                )
                db.session.add(log_entry)

                if result['ok']:
                    results['sent'].append({'name': mgr.full_name, 'number': mobile, 'type': 'manager'})
                else:
                    results['failed'].append({'name': mgr.full_name, 'error': result.get('error', '')})

            # Extra manually configured manager numbers
            for num in cfg.manager_numbers:
                if not num or num in mgr_numbers_sent:
                    continue
                mgr_numbers_sent.add(num)
                result = send_whatsapp(to=num, message=manager_msg, config=cfg)
                log_entry = NPDWhatsAppSendLog(
                    send_date     = for_date,
                    recipient_type= 'manager',
                    recipient_name= num,
                    mobile_number = num,
                    message_type  = 'manager_summary',
                    status        = 'sent' if result['ok'] else 'failed',
                    error_message = result.get('error', ''),
                    triggered_by  = triggered_by,
                )
                db.session.add(log_entry)
                if result['ok']:
                    results['sent'].append({'name': num, 'number': num, 'type': 'manager_extra'})
                else:
                    results['failed'].append({'name': num, 'error': result.get('error', '')})

        try:
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            logger.error(f'[NPD WA] DB commit error: {e}')

        summary = {
            'ok':      True,
            'date':    for_date.isoformat(),
            'sent':    len(results['sent']),
            'failed':  len(results['failed']),
            'skipped': len(results['skipped']),
            'details': results,
        }
        logger.info(f'[NPD WA] Done — sent={summary["sent"]}, failed={summary["failed"]}')
        return summary


# ─────────────────────────────────────────────────────────────
# APScheduler Integration
# ─────────────────────────────────────────────────────────────

def start_whatsapp_scheduler(app):
    """
    Start the background scheduler that auto-sends daily reports.
    Call once from index.py after app is fully configured:

        from npd_whatsapp_auto import start_whatsapp_scheduler
        start_whatsapp_scheduler(app)

    The send time is read from the database config (npd_whatsapp_config.send_time).
    If the config changes, restart the app or call reschedule_whatsapp_job().
    """
    try:
        from apscheduler.schedulers.background import BackgroundScheduler
        from apscheduler.triggers.cron import CronTrigger
        import atexit
    except ImportError:
        logger.warning(
            '[NPD WA] APScheduler not installed. '
            'Run: pip install apscheduler\n'
            'Without it, auto-send will not work. '
            'Use cron or the manual "Send Now" button instead.'
        )
        return None

    with app.app_context():
        try:
            from models.npd_daily_report import NPDWhatsAppConfig
            cfg_row = NPDWhatsAppConfig.query.first()
            send_time = (cfg_row.send_time if cfg_row else None) or '21:00'
        except Exception:
            send_time = '21:00'

    try:
        hour, minute = map(int, send_time.split(':'))
    except Exception:
        hour, minute = 21, 0

    scheduler = BackgroundScheduler(timezone='Asia/Kolkata')

    def _job():
        try:
            result = send_daily_reports(app)
            logger.info(f'[NPD WA Scheduler] {result}')
        except Exception as e:
            logger.error(f'[NPD WA Scheduler] Error: {e}')

    scheduler.add_job(
        func    = _job,
        trigger = CronTrigger(hour=hour, minute=minute, timezone='Asia/Kolkata'),
        id      = 'npd_daily_whatsapp',
        name    = 'NPD Daily WhatsApp Report',
        replace_existing = True,
        misfire_grace_time = 600,   # allow up to 10 min late start
    )

    scheduler.start()
    atexit.register(lambda: scheduler.shutdown(wait=False))

    logger.info(f'[NPD WA] Scheduler started — daily send at {send_time} IST')
    return scheduler


def reschedule_whatsapp_job(scheduler, new_time: str):
    """
    Update the scheduled send time without restarting the app.
    Called from the Admin Config UI when send time is changed.
    """
    if not scheduler:
        return False
    try:
        from apscheduler.triggers.cron import CronTrigger
        hour, minute = map(int, new_time.split(':'))
        scheduler.reschedule_job(
            'npd_daily_whatsapp',
            trigger=CronTrigger(hour=hour, minute=minute, timezone='Asia/Kolkata')
        )
        logger.info(f'[NPD WA] Rescheduled to {new_time} IST')
        return True
    except Exception as e:
        logger.error(f'[NPD WA] Reschedule error: {e}')
        return False
